# fly.toml app configuration file generated for boot-test2 on 2025-04-08T12:25:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'boot-test2'
[build]
  dockerfile = "Dockerfile"

primary_region = 'iad'

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

